Disallow actions while workspace is being initially created
upsidelab/physionet-build pull request #49
Opened 2022-03-08 11:42 UTC by adrianryt

2022-03-08 13:19 UTC, kshalot requested changes

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/models.py
> +    is_workspace_done = models.BooleanField(default=False)
I'd rename it into something different, e.g. `initial_workspace_setup_done`

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/services.py
> +    return True if workspace_details["workspace-setup-status"] == "workspace-setup-done" else False
```suggestion
    return workspace_details["workspace-setup-status"] == "workspace-setup-done"
```

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/services.py
> +    return True if workspace_details["workspace-setup-status"] == "workspace-setup-done" else False
Also I'd introduce a new entity into `entities.py` - a `ResearchWorkspace` dataclass that would have an enum status. Then you can do:
```python
return workspace_details.status == WorkspaceStatus.DONE
```

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/research_environments.html
> +    </div>
🤔

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/research_environments.html
> +    </div>
What's that?

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +    <h1>Research Environments Home</h1>
We could also extract a base template from this, e.g. `base_environment_home` that would have the `jumbotron` title and `lead`, all the css/js and a `content` block or the actual specific templates

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +    <h1>Research Environments Home</h1>
Because right now you have two templates that use the same layout - this physionet-django/environment/templates/environment/workspace_being_provisioned.html and also the acutal list view

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +    function check_workspace_status() {
I'd stick to camelCasing all the JS stuff

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +    let workspaceInterval = setInterval(check_workspace_status, 15000);
```suggestion
    const workspaceInterval = setInterval(check_workspace_status, 15000);
```
I don't see it reassigned anywhere

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +            method: 'GET',
```suggestion
            method: "GET",
```

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/templates/environment/workspace_being_provisioned.html
> +        fetch("{{ is_workspace_done_url }}",{
```suggestion
        fetch("{% url is_workspace_done %}",{
```

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/views.py
> +from django.urls import reverse
You don't need this, see other comments

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/views.py
> +            "is_workspace_done_url": reverse("is_workspace_setup_done"),
You don't need this, see other comments

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/views.py
> +            return redirect("workspace_setup")
This is a mistake, no?
```suggestion
            return redirect("research_environments")
```

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/views.py
> +            return redirect("workspace_setup")
Why redirect there if it's already set up anyway

2022-03-08 13:19 UTC, kshalot commented on physionet-django/environment/views.py
> +def is_workspace_setup_done(request):
```suggestion
@require_GET
@login_required
@cloud_identity_required
@billing_setup_required
def is_workspace_setup_done(request):
```

2022-03-09 08:18 UTC, adrianryt commented on physionet-django/environment/templates/environment/research_environments.html
> +    </div>
There was a missing </div> in a file

2022-03-15 16:22 UTC, merged